import 'reflect-metadata';
import smoothscroll from 'smoothscroll-polyfill';
import { createApp } from 'vue';
import App from './App.vue';
import DateTimePicker from './components/compat/DateTimePicker.vue';
import IChannelModel from './model/channels/IChannelModel';
import container from './model/ModelContainer';
import setter from './model/ModelContainerSetter';
import IPWAConfigModel from './model/pwa/IPWAConfigModel';
import IServerConfigModel from './model/serverConfig/IServerConfigModel';
import vuetify from './plugins/vuetify';
import router from './router';
setter(container);
smoothscroll.polyfill();
(async (): Promise<void> => {
    const serverConfigModel = container.get<IServerConfigModel>('IServerConfigModel');
    await serverConfigModel.fetchConfig().catch(err => console.error('get server config error', err));
    container.get<IPWAConfigModel>('IPWAConfigModel').setting();
    await container.get<IChannelModel>('IChannelModel').fetchChannels().catch(err => console.error('get channels error', err));
    const app = createApp(App);
    app.component('v-datetime-picker', DateTimePicker);
    app.use(router).use(vuetify).mount('#app');
})();
