name: build

on:
  push:
  workflow_dispatch:
    branches: [ main, master, test ]

jobs:
  build:

    name: build-${{matrix.os}}-${{matrix.node-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: EPGStation

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: install winser on windows
      if: runner.os == 'Windows'
      run: npm install winser -g
      
    - name: Mirakurun Checkout
      uses: actions/checkout@v4
      with:
        ref: feature/4.0.0-windows
        repository: stuayu/Mirakurun
        path: Mirakurun
    
    - name: Mirakurun build and install
      working-directory: Mirakurun
      continue-on-error: true # npm audit fixでエラーになるのを回避
      run: |
        npm install -g yarn
        yarn install
    
    - name: Install all
      working-directory: EPGStation
      continue-on-error: true # npm audit fixでエラーになるのを回避
      run: |
        yarn run all-install
      
    - name: Build EPGStation
      working-directory: EPGStation
      if: runner.os == 'Windows'
      run: yarn run build-win
    
    - name: Build EPGStation
      working-directory: EPGStation
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: yarn run build

    - name: Compress Project
      run: |
        7z a -m0=LZMA2 -mx=9 -md=128m -mfb=128 -ms=16g -mmt=on -mf=BCJ EPGStation-${{ matrix.os }}-${{ matrix.node-version }}.7z ./EPGStation
        7z a -m0=LZMA2 -mx=9 -md=128m -mfb=128 -ms=16g -mmt=on -mf=BCJ Mirakurun-${{ matrix.os }}-${{ matrix.node-version }}.7z ./Mirakurun

    - name: Upload Project as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EPGStation-${{ matrix.os }}-${{ matrix.node-version }}.7z
        path: EPGStation-${{ matrix.os }}-${{ matrix.node-version }}.7z
    
    - name: Upload Project as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mirakurun-${{ matrix.os }}-${{ matrix.node-version }}.7z
        path: Mirakurun-${{ matrix.os }}-${{ matrix.node-version }}.7z